// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © wbburgin (modificado)

//@version=5
indicator('Discrete Fourier Transform Overlay [Doble DFT]', shorttitle='DFT Overlay Doble', overlay=true, 
 max_bars_back=2000, max_lines_count=500)

import jdehorty/KernelFunctions/2 as kernel

//================================== FUNCIONES ==================================//
DFT(x, y, Nx, _dir) =>
    float _arg = 0.0
    float _cos = 0.0
    float _sin = 0.0
    float xArr_i = 0.0
    float yArr_i = 0.0
    xArr = array.new_float(array.size(x))
    yArr = array.new_float(array.size(y))

    for i = 0 to Nx - 1
        xArr_i := 0.0
        yArr_i := 0.0
        kx = float(i) / float(Nx)
        _arg := -_dir * 2 * math.pi * kx
        for k = 0 to Nx - 1
            _cos := math.cos(k * _arg)
            _sin := math.sin(k * _arg)
            xArr_i += array.get(x, k) * _cos - array.get(y, k) * _sin
            yArr_i += array.get(x, k) * _sin + array.get(y, k) * _cos
        array.set(xArr, i, xArr_i)
        array.set(yArr, i, yArr_i)

    if _dir == 1
        for i = 0 to Nx - 1
            array.set(x, i, array.get(xArr, i) / float(Nx))
            array.set(y, i, array.get(yArr, i) / float(Nx))
    else
        for i = 0 to Nx - 1
            array.set(x, i, array.get(xArr, i))
            array.set(y, i, array.get(yArr, i))

//================================= PRIMER DFT =================================//
N1 = input.int(20, "Fourier Period 1")
xval1 = input.source(close, "Fourier X Series 1")
highlighting1 = input.bool(true, "Highlighting 1")
smoothing1 = input.int(10, "Kernel Smoothing 1")

x1 = array.new_float(N1, 0.0)
y1 = array.new_float(N1, 0.0)
for i = 0 to N1 - 1
    array.set(x1, i, xval1[i])
    array.set(y1, i, 0.0)

DFT(x1, y1, N1, 1)

mag1 = array.new_float(N1, 0.0)
for i = 0 to N1 - 1
    mag_i1 = math.sqrt(math.pow(array.get(x1, i), 2) + math.pow(array.get(y1, i), 2))
    array.set(mag1, i, mag_i1)

dft1 = array.get(mag1, 0)
dfts1 = kernel.rationalQuadratic(dft1, 25, 1, smoothing1)

ft1 = plot(dft1, "DFT 1", color=color.white)
fts1 = plot(dfts1, "Smoothing 1", color=dfts1 > dft1 ? color.red : color.lime)
fill(ft1, fts1, color=highlighting1 and dfts1 > dft1 ? color.new(color.red, 75) : highlighting1 and dfts1 < dft1 ? color.new(color.lime, 75) : na)


//================================= SEGUNDO DFT =================================//
N2 = input.int(120, "Fourier Period 2", inline="dft2")
xval2 = input.source(close, "", inline="dft2")
highlighting2 = input.bool(true, "Highlighting 2")
smoothing2 = input.int(60, "Kernel Smoothing 2")

x2 = array.new_float(N2, 0.0)
y2 = array.new_float(N2, 0.0)
for i = 0 to N2 - 1
    array.set(x2, i, xval2[i])
    array.set(y2, i, 0.0)

DFT(x2, y2, N2, 1)

mag2 = array.new_float(N2, 0.0)
for i = 0 to N2 - 1
    mag_i2 = math.sqrt(math.pow(array.get(x2, i), 2) + math.pow(array.get(y2, i), 2))
    array.set(mag2, i, mag_i2)

dft2 = array.get(mag2, 0)
dfts2 = kernel.rationalQuadratic(dft2, 25, 1, smoothing2)

ft2 = plot(dft2, "DFT 2", color=color.white)
fts2 = plot(dfts2, "Smoothing 2", color=dfts2 > dft2 ? color.red : color.lime)
fill(ft2, fts2, color=highlighting2 and dfts2 > dft2 ? color.new(color.red, 75) : highlighting2 and dfts2 < dft2 ? color.new(color.lime, 75) : na)
